# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "janus"
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Julien Portalier"]
  s.date = "2012-01-30"
  s.description = "Authentication engine for Ruby on Rails."
  s.email = "ysbaddaden@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "lib/janus.rb",
    "lib/janus/config.rb",
    "lib/janus/controllers/confirmations_controller.rb",
    "lib/janus/controllers/helpers.rb",
    "lib/janus/controllers/internal_helpers.rb",
    "lib/janus/controllers/passwords_controller.rb",
    "lib/janus/controllers/registrations_controller.rb",
    "lib/janus/controllers/sessions_controller.rb",
    "lib/janus/controllers/url_helpers.rb",
    "lib/janus/helper.rb",
    "lib/janus/hooks.rb",
    "lib/janus/hooks/rememberable.rb",
    "lib/janus/hooks/remote_authenticatable.rb",
    "lib/janus/hooks/trackable.rb",
    "lib/janus/mailer.rb",
    "lib/janus/manager.rb",
    "lib/janus/models/base.rb",
    "lib/janus/models/confirmable.rb",
    "lib/janus/models/database_authenticatable.rb",
    "lib/janus/models/rememberable.rb",
    "lib/janus/models/remote_authenticatable.rb",
    "lib/janus/models/remote_token.rb",
    "lib/janus/models/trackable.rb",
    "lib/janus/rails.rb",
    "lib/janus/routes.rb",
    "lib/janus/sinatra.rb",
    "lib/janus/strategies.rb",
    "lib/janus/strategies/base.rb",
    "lib/janus/strategies/database_authenticatable.rb",
    "lib/janus/strategies/rememberable.rb",
    "lib/janus/strategies/remote_authenticatable.rb",
    "lib/janus/test_helper.rb"
  ]
  s.homepage = "http://github.com/ysbaddaden/janus"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Authentication engine for Ruby on Rails."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bcrypt-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<addressable>, [">= 0"])
    else
      s.add_dependency(%q<bcrypt-ruby>, [">= 0"])
      s.add_dependency(%q<addressable>, [">= 0"])
    end
  else
    s.add_dependency(%q<bcrypt-ruby>, [">= 0"])
    s.add_dependency(%q<addressable>, [">= 0"])
  end
end

