source 'http://rubygems.org'

gem 'rails', '3.0.5'
#gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'sqlite3'
gem 'capybara'
gem 'addressable', :require => 'addressable/uri'
gem 'janus', :path => '../..'

